<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <groupId>ru.chessinsight</groupId>
    <artifactId>chessinsight</artifactId>
    <version>1.0.0</version>
    <packaging>pom</packaging>
    <name>ChessInsight</name>
    <description>ChessInsight - Chess Analysis and Training App</description>

    <modules>
        <module>core</module>
        <module>cli</module>
        <module>engine</module>
        <module>jpa</module>
    </modules>

    <properties>
        <java.version>24</java.version>
        <spring-boot.version>3.4.5</spring-boot.version>
        <bytebuddy.version>1.17.5</bytebuddy.version>
        <testcontainers.version>1.20.1</testcontainers.version>
    </properties>

    <parent>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter-parent</artifactId>
        <version>3.4.5</version>
        <relativePath/>
    </parent>

    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>org.testcontainers</groupId>
                <artifactId>testcontainers-bom</artifactId>
                <version>1.21.3</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
        </dependencies>
    </dependencyManagement>
</project>
