logging.level.org.springframework=ERROR
logging.level.org.hibernate=ERROR
logging.level.root=ERROR
spring.main.banner-mode=off

spring.datasource.url=jdbc:postgresql://postgres:5432/chess_insight
spring.datasource.username=admin
spring.datasource.password=admin
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=none

engine.stockfish.mode=tcp
engine.stockfish.host=stockfish
engine.stockfish.port=5555
engine.stockfish.path=/usr/local/bin/stockfish
engine.stockfish.defaultDepth=15

spring.data.redis.host=redis
spring.data.redis.port=6379
spring.data.redis.timeout=10s
jwt.secret=super-secret-key-1234567890-super-secret-key-SECURITY-IS-MY-FIRST-NAME-ilovebeingsecure-qwerty
jwt.expiration=3600
