logging.level.org.springframework=ERROR
logging.level.org.hibernate=ERROR
logging.level.root=ERROR
logging.level.ru.chessinsight=INFO
spring.main.banner-mode=off

chess.api.base-url=http://localhost/api/v1
