worker_processes auto;

events {
  worker_connections 1024;
}

http {
  include /etc/nginx/mime.types;
  default_type application/octet-stream;
  types { text/markdown md; }
  sendfile on;
  keepalive_timeout 65;

  server_tokens off;

  log_format upstream '$remote_addr - $remote_user [$time_local] "$request" '
                      '$status $body_bytes_sent "$http_referer" '
                      '"$http_user_agent" "$upstream_addr" "$upstream_status" "$request_time"';
  access_log /var/log/nginx/access.log upstream;

  gzip on;
  gzip_min_length 256;
  gzip_comp_level 5;
  gzip_proxied any;
  gzip_types
    text/plain
    text/css
    application/json
    application/javascript
    text/xml
    application/xml
    application/xml+rss
    text/javascript
    image/svg+xml
    application/vnd.ms-fontobject
    application/x-font-ttf
    font/opentype;

  include /etc/nginx/conf.d/*.conf;
}
