spring.data.redis.host=redis
spring.data.redis.port=6379
spring.data.redis.timeout=10s
#engine.stockfish.path=/usr/local/bin/stockfish
#engine.stockfish.defaultDepth=8
jwt.secret=super-secret-key-1234567890-super-secret-key-SECURITY-IS-MY-FIRST-NAME-ilovebeingsecure-qwerty
jwt.expiration=3600
