#!/bin/sh
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
DO \$\$
BEGIN
  IF NOT EXISTS (SELECT FROM pg_roles WHERE rolname = '${READONLY_USER}') THEN
    CREATE ROLE "${READONLY_USER}" LOGIN PASSWORD '${READONLY_PASSWORD}';
  END IF;
  IF NOT EXISTS (SELECT FROM pg_roles WHERE rolname = '${REPLICATION_USER}') THEN
    CREATE ROLE "${REPLICATION_USER}" REPLICATION LOGIN PASSWORD '${REPLICATION_PASSWORD}';
  END IF;
END
\$\$;

GRANT CONNECT ON DATABASE "${POSTGRES_DB}" TO "${READONLY_USER}";
GRANT USAGE ON SCHEMA public TO "${READONLY_USER}";
GRANT SELECT ON ALL TABLES IN SCHEMA public TO "${READONLY_USER}";
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT ON TABLES TO "${READONLY_USER}";
ALTER ROLE "${READONLY_USER}" SET default_transaction_read_only = on;
EOSQL

echo "host replication ${REPLICATION_USER} 0.0.0.0/0 md5" >> "$PGDATA/pg_hba.conf"
echo "host all ${READONLY_USER} 0.0.0.0/0 md5" >> "$PGDATA/pg_hba.conf"
